### ISSUE TITLE
App support for blind

### ISSUE THREAD

**Issue by kantoniak** [kantoniak/tap-the-map#3]
This is a parent issue for blind-user support etc. @kedzior please update issue with list of things to do.

**Comment by kantoniak** [comment]
Is it possible to integrate with TalkBack? https://developer.android.com/guide/topics/ui/accessibility/apps.html

**Comment by kedzior** [comment]
* Generate mp3 for new questions (PL/ENG?)
* Question reading - mostly done
* Selecting countries (might use talkback?)
* Result reading
* Avoid overlaping voices

**Comment by kantoniak** [comment]
The code moved to https://github.com/Statistics-Poland/tap-the-map, please follow their issue tracker.
